import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import * as jose from "https://deno.land/x/jose@v4.15.5/index.ts";

const PROJECT_ID = Deno.env.get("FIREBASE_PROJECT_ID") || "fittrack-698fa";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const FIRESTORE_BASE = `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents`;
const ALLOWED_ORIGINS = new Set(["https://bodyahmed77.github.io", "http://localhost", "https://localhost"]);
const sb = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });

function headers(req: Request) {
  const origin = req.headers.get("Origin") || "";
  return { ...(ALLOWED_ORIGINS.has(origin) ? { "Access-Control-Allow-Origin": origin, Vary: "Origin" } : {}), "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Cache-Control": "no-store" };
}
function json(req: Request, status: number, body: Record<string, unknown>) { return new Response(JSON.stringify(body), { status, headers: { ...headers(req), "Content-Type": "application/json" } }); }
async function firebaseUid(token: string) {
  const jwks = jose.createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));
  const { payload } = await jose.jwtVerify(token, jwks, { issuer: `https://securetoken.google.com/${PROJECT_ID}`, audience: PROJECT_ID });
  const uid = payload.sub || payload.user_id; if (!uid) throw new Error("missing_uid"); return String(uid);
}
async function assertAdmin(token: string, uid: string) {
  const r = await fetch(`${FIRESTORE_BASE}/admins/${encodeURIComponent(uid)}`, { headers: { Authorization: `Bearer ${token}` } });
  if (r.status === 404) return false; if (!r.ok) throw new Error(`admin_check_failed:${r.status}`);
  const data = await r.json(); const role = data?.fields?.role?.stringValue; return role == null || role === "" || role === "owner" || role === "staff";
}
function decode(v: any): any {
  if (!v || typeof v !== "object") return null;
  if ("nullValue" in v) return null; if ("stringValue" in v) return v.stringValue; if ("booleanValue" in v) return v.booleanValue;
  if ("integerValue" in v) return Number(v.integerValue); if ("doubleValue" in v) return Number(v.doubleValue); if ("timestampValue" in v) return v.timestampValue; if ("referenceValue" in v) return v.referenceValue;
  if (v.arrayValue) return (v.arrayValue.values || []).map(decode); if (v.mapValue) return decodeFields(v.mapValue.fields || {}); return null;
}
function decodeFields(fields: Record<string, any>) { const out: Record<string, any> = {}; for (const [k, v] of Object.entries(fields || {})) out[k] = decode(v); return out; }
async function firestoreGetUser(token: string, uid: string) {
  const r = await fetch(`${FIRESTORE_BASE}/users/${encodeURIComponent(uid)}`, { headers: { Authorization: `Bearer ${token}` } }); if (r.status === 404) return null; if (!r.ok) throw new Error(`firestore_read_failed:${r.status}`); return r.json();
}
async function firestoreSearchEmail(token: string, email: string) {
  const r = await fetch(`${FIRESTORE_BASE}:runQuery`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ structuredQuery: { from: [{ collectionId: "users" }], where: { fieldFilter: { field: { fieldPath: "account.email" }, op: "EQUAL", value: { stringValue: email } } }, limit: 10 } }) });
  if (!r.ok) throw new Error(`firestore_search_failed:${r.status}`); const rows = await r.json(); return (Array.isArray(rows) ? rows : []).filter((x) => x?.document?.name).map((x) => ({ uid: String(x.document.name).split("/users/")[1] || "", data: decodeFields(x.document.fields || {}) })).filter((x) => x.uid);
}
async function firestoreListUsers(token: string, limitValue = 200) {
  const limit = Math.min(Math.max(Number(limitValue) || 200, 1), 200);
  const r = await fetch(`${FIRESTORE_BASE}:runQuery`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ structuredQuery: { from: [{ collectionId: "users" }], limit } }) });
  if (!r.ok) throw new Error(`firestore_list_failed:${r.status}`); const rows = await r.json(); return (Array.isArray(rows) ? rows : []).filter((x) => x?.document?.name).map((x) => ({ uid: String(x.document.name).split("/users/")[1] || "", data: decodeFields(x.document.fields || {}) })).filter((x) => x.uid);
}
async function firestoreCountUsers(token: string) {
  const r = await fetch(`${FIRESTORE_BASE}:runAggregationQuery`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ structuredAggregationQuery: { structuredQuery: { from: [{ collectionId: "users" }] }, aggregations: [{ count: { alias: "customerCount" } }] } }) });
  if (!r.ok) throw new Error(`firestore_count_failed:${r.status}`); const rows = await r.json(); const value = rows?.[0]?.result?.aggregateFields?.customerCount; return Number(value?.integerValue || value?.doubleValue || 0);
}
function scalar(v: unknown): Record<string, unknown> { if (typeof v === "boolean") return { booleanValue: v }; if (typeof v === "number" && Number.isFinite(v)) return { doubleValue: v }; if (typeof v === "string") return { stringValue: v }; return { nullValue: null }; }
function buildFields(values: Record<string, unknown>) { const root: Record<string, any> = {}; for (const [path, value] of Object.entries(values)) { const p = path.split("."); let node = root; for (let i = 0; i < p.length - 1; i += 1) { if (!node[p[i]]) node[p[i]] = { mapValue: { fields: {} } }; node = node[p[i]].mapValue.fields; } node[p[p.length - 1]] = scalar(value); } return root; }
async function firestorePatch(token: string, uid: string, values: Record<string, unknown>) { const mask = Object.keys(values).map((x) => `updateMask.fieldPaths=${encodeURIComponent(x)}`).join("&"); const r = await fetch(`${FIRESTORE_BASE}/users/${encodeURIComponent(uid)}?${mask}`, { method: "PATCH", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ fields: buildFields(values) }) }); if (!r.ok) { const detail = await r.text().catch(() => ""); throw new Error(`firestore_write_failed:${r.status}:${detail.slice(0, 200)}`); } }
async function notify(token: string, uid: string, title: string, body: string) { const id = crypto.randomUUID().replaceAll("-", ""); const r = await fetch(`${FIRESTORE_BASE}/users/${encodeURIComponent(uid)}/notifications?documentId=${id}`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ fields: { title: { stringValue: title.slice(0, 100) }, body: { stringValue: body.slice(0, 1000) }, createdAt: { timestampValue: new Date().toISOString() }, read: { booleanValue: false } } }) }); if (!r.ok) throw new Error(`firestore_notification_failed:${r.status}`); }
function parseExpiry(value: unknown) { const raw = value == null ? "" : String(value).trim(); if (!raw) return { raw: null as string | null, valid: false, ms: NaN }; const ms = /^\d{4}-\d{2}-\d{2}$/.test(raw) ? Date.parse(`${raw}T23:59:59.999Z`) : Date.parse(raw); return { raw, valid: Number.isFinite(ms), ms }; }
function activeExpiry(value: unknown) { const p = parseExpiry(value); return p.valid && p.ms > Date.now(); }
function adminEntitlements(doc: any) { const f = doc?.fields?.adminEntitlements?.mapValue?.fields || {}; const expiry = f?.proExpiresAt?.stringValue ? String(f.proExpiresAt.stringValue) : null; if (!activeExpiry(expiry)) return { trainingPro: false, nutritionPro: false, aiCoachPro: false, proExpiresAt: null }; const flag = (k: string) => f?.[k]?.booleanValue === true; return { trainingPro: flag("trainingPro"), nutritionPro: flag("nutritionPro"), aiCoachPro: flag("aiCoachPro"), proExpiresAt: expiry }; }
async function countRows(table: string, fn?: (q: any) => any) { let q = sb.from(table).select("id", { count: "exact", head: true }); if (fn) q = fn(q); const { count, error } = await q; if (error) throw error; return Number(count || 0); }
async function overview() { const since24 = new Date(Date.now()-86400000).toISOString(); const since7 = new Date(Date.now()-7*86400000).toISOString(); const [openReports, activeEntitlements, billing24h, reports7d, audit7d] = await Promise.all([countRows("ai_reports", q=>q.eq("status","open")), countRows("entitlements", q=>q.eq("purchase_state","active")), countRows("billing_event_log", q=>q.gte("created_at",since24)), countRows("ai_reports", q=>q.gte("created_at",since7)), countRows("admin_audit_log", q=>q.gte("created_at",since7))]); const {data:usage,error:usageError}=await sb.from("ai_usage").select("count").eq("usage_date",new Date().toISOString().slice(0,10)); if(usageError)throw usageError; const aiMessagesToday=(usage||[]).reduce((s,r)=>s+Number(r.count||0),0); const {data:products,error:productError}=await sb.from("entitlements").select("product_key").eq("purchase_state","active"); if(productError)throw productError; const byProduct:Record<string,number>={}; for(const r of products||[])byProduct[r.product_key]=(byProduct[r.product_key]||0)+1; return {stats:{openReports,activeEntitlements,billing24h,aiMessagesToday,reports7d,audit7d},activeEntitlementsByProduct:byProduct,generatedAt:new Date().toISOString()}; }
async function recentReports(status:string|null,lim:number){let q=sb.from("ai_reports").select("id,uid,response_text,reason,lang,created_at,status,model,reviewed_at,reviewed_by").order("created_at",{ascending:false}).limit(Math.min(Math.max(lim||50,1),100)); if(status&&["open","reviewed","dismissed"].includes(status))q=q.eq("status",status); const {data,error}=await q;if(error)throw error;return data||[];}
async function recentBilling(lim:number){const {data,error}=await sb.from("billing_event_log").select("id,uid,product_key,event_type,purchase_state,expires_at,purchase_token_present,created_at").order("created_at",{ascending:false}).limit(Math.min(Math.max(lim||50,1),100));if(error)throw error;return data||[];}
async function recentAudit(lim:number){const {data,error}=await sb.from("admin_audit_log").select("id,admin_uid,action,target_type,target_id,metadata,created_at").order("created_at",{ascending:false}).limit(Math.min(Math.max(lim||50,1),100));if(error)throw error;return data||[];}
async function audit(adminUid:string,action:string,targetType:string,targetId:string,metadata:Record<string,unknown>={}){const {error}=await sb.from("admin_audit_log").insert({admin_uid:adminUid,action,target_type:targetType,target_id:targetId,metadata});if(error)throw error;}
async function updateReport(adminUid:string,id:string,status:string){if(!id||!["open","reviewed","dismissed"].includes(status))throw new Error("invalid_report_update");const reviewed=status==="open"?null:new Date().toISOString();const reviewedBy=status==="open"?null:adminUid;const {data,error}=await sb.from("ai_reports").update({status,reviewed_at:reviewed,reviewed_by:reviewedBy}).eq("id",id).select("id,uid,status,reviewed_at,reviewed_by").single();if(error)throw error;await audit(adminUid,"report_status_update","ai_report",id,{status});return data;}
async function updateAccount(token:string,adminUid:string,uid:string,name?:string,phone?:string){if(!uid)throw new Error("target_uid_required");const v:Record<string,unknown>={};if(typeof name==="string")v["account.name"]=name.trim().slice(0,120);if(typeof phone==="string")v["account.phone"]=phone.trim().slice(0,40);if(!Object.keys(v).length)throw new Error("no_account_changes");v.updatedAt=new Date().toISOString();await firestorePatch(token,uid,v);await audit(adminUid,"user_account_update","firebase_user",uid,{fields:Object.keys(v).filter(k=>k!=="updatedAt")});return {ok:true};}
async function updateSupport(token:string,adminUid:string,uid:string,changes:any){if(!uid||!changes||typeof changes!=="object")throw new Error("invalid_entitlement_change");const allowed=["trainingPro","nutritionPro","aiCoachPro"];if(!allowed.some(k=>Object.prototype.hasOwnProperty.call(changes,k)))throw new Error("no_entitlement_change");const current=adminEntitlements(await firestoreGetUser(token,uid));const next={...current};for(const k of allowed)if(changes[k]!==undefined)next[k]=changes[k]===true;const any=next.trainingPro||next.nutritionPro||next.aiCoachPro;if(any){const requested=parseExpiry(changes.proExpiresAt);const existing=parseExpiry(next.proExpiresAt);if(requested.valid&&requested.ms>Date.now())next.proExpiresAt=requested.raw;else if(existing.valid&&existing.ms>Date.now())next.proExpiresAt=existing.raw;else throw new Error("future_support_expiry_required");}else next.proExpiresAt=null;await firestorePatch(token,uid,{"adminEntitlements.trainingPro":next.trainingPro,"adminEntitlements.nutritionPro":next.nutritionPro,"adminEntitlements.aiCoachPro":next.aiCoachPro,"adminEntitlements.proExpiresAt":next.proExpiresAt,updatedAt:new Date().toISOString()});await audit(adminUid,"admin_entitlement_update","firebase_user",uid,{changes,next});return next;}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:headers(req)});if(req.method!=="POST")return json(req,405,{error:"method_not_allowed"});if(!SUPABASE_URL||!SERVICE_KEY)return json(req,500,{error:"backend_error"});const match=(req.headers.get("Authorization")||"").match(/^Bearer\s+(.+)$/i);if(!match)return json(req,401,{error:"unauthenticated"});const token=match[1].trim();let uid="";try{uid=await firebaseUid(token);if(!(await assertAdmin(token,uid)))return json(req,403,{error:"forbidden"});}catch(e){console.error("admin auth failed",e);return json(req,401,{error:"unauthenticated"});}let body:Record<string,unknown>={};try{body=await req.json();}catch{return json(req,400,{error:"bad_request"});}const action=String(body.action||"");try{switch(action){case"overview":return json(req,200,{ok:true,data:await overview()});case"users_count":return json(req,200,{ok:true,data:await firestoreCountUsers(token)});case"users_list":return json(req,200,{ok:true,data:await firestoreListUsers(token,Number(body.limit||200))});case"users_search":return json(req,200,{ok:true,data:await firestoreSearchEmail(token,String(body.email||"").trim().toLowerCase().slice(0,200))});case"reports_list":return json(req,200,{ok:true,data:await recentReports(body.status?String(body.status):null,Number(body.limit||50))});case"billing_recent":return json(req,200,{ok:true,data:await recentBilling(Number(body.limit||50))});case"audit_recent":return json(req,200,{ok:true,data:await recentAudit(Number(body.limit||50))});case"report_update":return json(req,200,{ok:true,data:await updateReport(uid,String(body.id||""),String(body.status||""))});case"user_account_update":return json(req,200,{ok:true,data:await updateAccount(token,uid,String(body.targetUid||""),typeof body.name==="string"?body.name:undefined,typeof body.phone==="string"?body.phone:undefined)});case"user_pro_update":return json(req,200,{ok:true,data:await updateSupport(token,uid,String(body.targetUid||""),body.changes)});case"send_notification":await notify(token,String(body.targetUid||""),String(body.title||"Fifty Fit"),String(body.body||""));await audit(uid,"notification_sent","firebase_user",String(body.targetUid||""),{title:String(body.title||"Fifty Fit")});return json(req,200,{ok:true,data:{sent:true}});default:return json(req,400,{error:"unknown_action"});}}catch(e){console.error("admin action failed",e);return json(req,400,{error:String(e?.message||"admin_action_failed").slice(0,200)});}});
