import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Apple, Bot, CalendarDays, Check, ChevronRight, Crown, Dumbbell, Flame, Home, LineChart, Play, Settings, Sparkles, Target, Utensils, Weight, X, Zap } from "lucide-react";
import "./styles.css";

const TODAY = new Date().toLocaleDateString("en-CA");
const seed = {name:"Demo Athlete",weight:72,goal:"Build Muscle",calories:2850,macros:{protein:150,carbs:350,fat:90},workoutStartDate:TODAY,completed:false};

function App(){
 const [tab,setTab]=useState("home");
 const [data,setData]=useState(()=>{try{return {...seed,...JSON.parse(localStorage.getItem("fiftyfit-demo-profile")||"{}")};}catch{return seed;}});
 const [aiOpen,setAiOpen]=useState(false),[aiInput,setAiInput]=useState(""),[toast,setToast]=useState("");
 const [messages,setMessages]=useState([{role:"assistant",text:"Hey! I’m your Fifty Fit demo coach. Ask me about training, nutrition, recovery or progression."}]);
 const save=next=>{setData(next);try{localStorage.setItem("fiftyfit-demo-profile",JSON.stringify(next));}catch{}};
 const dayOneLabel=useMemo(()=>`Day 1 • ${new Date(`${data.workoutStartDate}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}`,[data.workoutStartDate]);
 const showToast=msg=>{setToast(msg);window.setTimeout(()=>setToast(""),1800);};
 const reply=()=>{const q=aiInput.trim();if(!q)return;const low=q.toLowerCase();let text="Be consistent, use progressive overload, eat enough protein, and recover well. Tell me your goal and exercise for a more specific answer.";if(low.includes("protein"))text="Your demo target is 150 g protein/day. Spread protein across meals and pair it with progressive resistance training.";else if(low.includes("calorie")||low.includes("bulk"))text="For gaining, use a modest calorie surplus and follow your weekly trend. Your demo target is 2,850 kcal/day.";else if(low.includes("bench")||low.includes("chest"))text="Keep a stable setup, controlled lowering, and add reps/load only while technique stays solid. Most work can stay around 1–3 reps in reserve.";else if(low.includes("rest")||low.includes("recovery"))text="Recovery is part of progression. Sleep well, use appropriate rest periods, and avoid taking every set to failure.";setMessages(m=>[...m,{role:"user",text:q},{role:"assistant",text}]);setAiInput("");};
 const completeWorkout=()=>{save({...data,completed:true});showToast("Workout completed • Progress saved");};
 return <div className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">F5</div><div><strong>Fifty Fit</strong><span>TRAIN • EAT • PROGRESS</span></div></div><div className="demo-pill"><Sparkles size={14}/> DEMO MODE</div></header><main className="content">
 {tab==="home"&&<HomeView data={data} dayOneLabel={dayOneLabel} onStart={()=>setTab("workout")} onAI={()=>setAiOpen(true)}/>} {tab==="workout"&&<WorkoutView completed={data.completed} onComplete={completeWorkout}/>} {tab==="nutrition"&&<NutritionView data={data}/>} {tab==="progress"&&<ProgressView data={data}/>} {tab==="settings"&&<SettingsView data={data} save={save}/>}</main>
 <nav className="bottom-nav">{[["home",Home,"Home"],["workout",Dumbbell,"Train"],["nutrition",Apple,"Nutrition"],["progress",LineChart,"Progress"],["settings",Settings,"Settings"]].map(([id,Icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={19}/><span>{label}</span></button>)}</nav>
 <button className="ai-fab" onClick={()=>setAiOpen(true)}><Bot size={20}/><span>AI Coach</span></button>
 {aiOpen&&<div className="modal-backdrop" onClick={()=>setAiOpen(false)}><div className="ai-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow"><Bot size={15}/> AI COACH</div><h2>Your fitness copilot</h2></div><button className="icon-btn" onClick={()=>setAiOpen(false)}><X/></button></div><div className="chat">{messages.map((m,i)=><div key={i} className={`msg ${m.role}`}>{m.text}</div>)}</div><div className="chat-input"><input value={aiInput} onChange={e=>setAiInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&reply()} placeholder="Ask about training or nutrition…"/><button onClick={reply}><ChevronRight/></button></div><div className="demo-note">Demo AI is simulated locally. Production AI stays server-authoritative.</div></div></div>}
 {toast&&<div className="toast"><Check size={16}/>{toast}</div>}</div>;
}
function HomeView({data,dayOneLabel,onStart,onAI}){return <><section className="hero"><div><div className="eyebrow">GOOD TO SEE YOU</div><h1>Ready to make today count?</h1><p>Your first training day starts today — no artificial rest-day offset.</p></div><div className="hero-badge"><Flame size={19}/><strong>{dayOneLabel}</strong></div></section><div className="stats-grid"><Stat icon={Weight} label="Weight" value={`${data.weight} kg`}/><Stat icon={Target} label="Goal" value={data.goal}/><Stat icon={Zap} label="Calories" value={`${data.calories}`}/></div><section className="card workout-card"><div className="card-title"><div><div className="eyebrow">TODAY'S WORKOUT</div><h2>Upper Body Strength</h2></div><span className="tag">Day 1</span></div>{[['Bench Press','4 sets • 6–10 reps'],['Lat Pulldown','3 sets • 8–12 reps'],['Lateral Raise','3 sets • 12–15 reps']].map(([n,s])=><div className="exercise-row" key={n}><div className="exercise-icon"><Dumbbell/></div><div><strong>{n}</strong><span>{s}</span></div><ChevronRight/></div>)}<button className="primary" onClick={onStart}><Play size={17}/> Start workout</button></section><div className="two-col"><section className="card"><div className="eyebrow">NUTRITION</div><h3>Daily target</h3><div className="big-number">{data.calories}<span> kcal</span></div><div className="macro-mini"><span>P {data.macros.protein}g</span><span>C {data.macros.carbs}g</span><span>F {data.macros.fat}g</span></div></section><section className="card ai-card" onClick={onAI}><div className="eyebrow"><Bot size={15}/> AI COACH</div><h3>Ask anything</h3><p>Training, calories, recovery, progression.</p><button className="secondary">Open coach <ChevronRight size={16}/></button></section></div></>}
function Stat({icon:Icon,label,value}){return <div className="stat"><Icon size={17}/><span>{label}</span><strong>{value}</strong></div>}
function WorkoutView({completed,onComplete}){return <section><div className="section-head"><div><div className="eyebrow">TODAY • DAY 1</div><h1>Upper Body Strength</h1></div><span className={completed?"tag success":"tag"}>{completed?"Completed":"Ready"}</span></div><div className="card">{[['Bench Press','4 × 6–10'],['Incline DB Press','3 × 8–12'],['Lat Pulldown','3 × 8–12'],['Seated Row','3 × 8–12'],['Lateral Raise','3 × 12–15']].map(([n,s])=><div className="exercise-row" key={n}><div className="exercise-icon"><Dumbbell/></div><div><strong>{n}</strong><span>{s} • Rest 90 sec</span></div><button className="mini-play"><Play size={14}/></button></div>)}<button className="primary" onClick={onComplete} disabled={completed}>{completed?<><Check/> Workout completed</>:<><Check/> Finish workout</>}</button></div></section>}
function NutritionView({data}){return <section><div className="section-head"><div><div className="eyebrow">NUTRITION</div><h1>Fuel your goal</h1></div><span className="tag">Custom targets</span></div><div className="nutrition-hero card"><div><div className="eyebrow">DAILY CALORIES</div><div className="big-number">{data.calories}<span> kcal</span></div></div><div className="cal-ring"><Apple size={26}/></div></div><div className="macro-grid"><Macro label="Protein" value={data.macros.protein} unit="g" icon={Target}/><Macro label="Carbs" value={data.macros.carbs} unit="g" icon={Utensils}/><Macro label="Fat" value={data.macros.fat} unit="g" icon={Activity}/></div><section className="card"><div className="eyebrow">DEMO LOG</div><h3>Meals today</h3><div className="meal"><span>Breakfast</span><strong>650 kcal</strong></div><div className="meal"><span>Lunch</span><strong>820 kcal</strong></div><div className="meal"><span>Snack</span><strong>280 kcal</strong></div></section></section>}
function Macro({label,value,unit,icon:Icon}){return <div className="card macro"><Icon size={18}/><span>{label}</span><strong>{value}<small>{unit}</small></strong></div>}
function ProgressView({data}){return <section><div className="section-head"><div><div className="eyebrow">PROGRESS</div><h1>Your momentum</h1></div></div><div className="progress-card card"><div className="progress-top"><div><span>Current weight</span><strong>{data.weight} kg</strong></div><div><span>Goal</span><strong>80 kg</strong></div></div><div className="chart"><div className="chart-line"><i/><i/><i/><i/><i/><i/></div></div><div className="progress-note"><Activity size={18}/><span>Log consistently to build a useful trend.</span></div></div><div className="stats-grid"><Stat icon={Check} label="Workouts" value={data.completed?"1":"0"}/><Stat icon={Flame} label="Streak" value={data.completed?"1 day":"0 days"}/><Stat icon={CalendarDays} label="Started" value={new Date(`${data.workoutStartDate}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}/></div></section>}
function SettingsView({data,save}){return <section><div className="section-head"><div><div className="eyebrow">SETTINGS</div><h1>Personalize Fifty Fit</h1></div></div><div className="card settings-list"><label>Name<input value={data.name} onChange={e=>save({...data,name:e.target.value})}/></label><label>Goal<select value={data.goal} onChange={e=>save({...data,goal:e.target.value})}><option>Build Muscle</option><option>Lose Fat</option><option>Maintain</option></select></label><div className="setting-row"><div><strong>Demo account</strong><span>All changes stay in this browser.</span></div><span className="tag success">Local</span></div></div><div className="card pro-banner"><div className="eyebrow"><Crown size={15}/> PRO</div><h3>Unlock the full Fifty Fit experience</h3><p>Adaptive plans, deeper nutrition tools and expanded AI coaching in the real app.</p><button className="primary" onClick={()=>window.alert("Demo purchase flow — no charge made.")}>View plans</button></div></section>}

createRoot(document.getElementById("root")).render(<App/>);
