#!/usr/bin/env python3
"""Validate the Google OAuth configuration and extract the Web client ID."""
from __future__ import annotations

import base64
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "googleWebClientId.js"
CAPACITOR_CONFIG = ROOT / "capacitor.config.json"
EXPECTED_PACKAGE = "com.bodyahmed77.fiftyfit"
EXPECTED_PLAY_SHA1 = "55384cf206854973c68dfba5be2a1bba8e048bee"
EXPECTED_UPLOAD_SHA1 = "c62c4d0c0ae964620887e464835de5196842131b"


def load_gs() -> dict:
    b64 = os.environ.get("GOOGLE_SERVICES_JSON_BASE64") or os.environ.get("GS_B64")
    if b64:
        raw = base64.b64decode(b64)
        return json.loads(raw.decode("utf-8"))
    path = Path(os.environ.get("GOOGLE_SERVICES_JSON", "android/app/google-services.json"))
    if not path.is_file():
        path = ROOT / "android" / "app" / "google-services.json"
    if not path.is_file():
        raise SystemExit("No google-services.json available (set GOOGLE_SERVICES_JSON_BASE64 or path)")
    return json.loads(path.read_text(encoding="utf-8"))


def find_web_client_id(data: dict) -> str:
    for client in data.get("client") or []:
        for oa in client.get("oauth_client") or []:
            if oa.get("client_type") == 3 and oa.get("client_id"):
                return str(oa["client_id"]).strip()
    for client in data.get("client") or []:
        for oa in client.get("oauth_client") or []:
            cid = (oa.get("client_id") or "").strip()
            if cid.endswith(".apps.googleusercontent.com") and not oa.get("android_info"):
                return cid
    raise SystemExit("No Web OAuth client_id (client_type 3) found in google-services.json")


def registered_sha1s(data: dict) -> set[str]:
    certs: set[str] = set()
    for client in data.get("client") or []:
        package = ((client.get("client_info") or {}).get("android_client_info") or {}).get("package_name")
        if package != EXPECTED_PACKAGE:
            continue
        for oa in client.get("oauth_client") or []:
            if oa.get("client_type") != 1:
                continue
            cert = str(((oa.get("android_info") or {}).get("certificate_hash") or "")).replace(":", "").lower()
            if cert:
                certs.add(cert)
    return certs


def inject_capacitor_config(web_client_id: str) -> None:
    if not CAPACITOR_CONFIG.is_file():
        raise SystemExit(f"Missing {CAPACITOR_CONFIG}")
    config = json.loads(CAPACITOR_CONFIG.read_text(encoding="utf-8"))
    auth = config.setdefault("plugins", {}).setdefault("FirebaseAuthentication", {})
    auth["skipNativeAuth"] = True
    providers = list(auth.get("providers") or [])
    if "google.com" not in providers:
        providers.append("google.com")
    auth["providers"] = providers
    auth["googleWebClientId"] = web_client_id
    CAPACITOR_CONFIG.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> None:
    data = load_gs()
    project_id = str(data.get("project_info", {}).get("project_id") or "")
    if project_id != "fittrack-698fa":
        raise SystemExit(f"Unexpected Firebase project_id: {project_id!r}")

    android_clients = [
        client
        for client in data.get("client") or []
        if ((client.get("client_info") or {}).get("android_client_info") or {}).get("package_name") == EXPECTED_PACKAGE
    ]
    if not android_clients:
        raise SystemExit(f"No Android client for {EXPECTED_PACKAGE} in google-services.json")

    certs = registered_sha1s(data)
    missing = [
        label
        for label, value in (
            ("Play App Signing SHA-1", EXPECTED_PLAY_SHA1),
            ("Upload SHA-1", EXPECTED_UPLOAD_SHA1),
        )
        if value not in certs
    ]
    if missing:
        raise SystemExit(
            "google-services.json is missing required OAuth SHA-1 entries: "
            f"{', '.join(missing)}; registered={sorted(certs)}"
        )

    client_id = find_web_client_id(data)
    content = (
        "/**\n"
        " * Google OAuth Web client ID (type 3 in google-services.json).\n"
        " * Generated by scripts/extract-google-web-client-id.py — do not edit by hand.\n"
        " */\n"
        f'export const GOOGLE_WEB_CLIENT_ID = "{client_id}";\n'
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    inject_capacitor_config(client_id)
    print(f"Google OAuth preflight OK: project={project_id}, package={EXPECTED_PACKAGE}")
    print(f"Play SHA-1 present: {EXPECTED_PLAY_SHA1}")
    print(f"Upload SHA-1 present: {EXPECTED_UPLOAD_SHA1}")
    print(f"Web client: …{client_id[-24:]}")
    print("Capacitor FirebaseAuthentication googleWebClientId injected")


if __name__ == "__main__":
    main()
