#!/usr/bin/env python3
"""Extract and validate the Web OAuth client ID used by Google Sign-In.

The Web (type 3) client ID is the server client ID consumed by the Android
Credential Manager Google ID flow. The value is also declared in
capacitor.config.json so the native FirebaseAuthentication plugin receives the
same client ID when the Android project is generated.
"""
from __future__ import annotations

import base64
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "googleWebClientId.js"
CAP_CONFIG = ROOT / "capacitor.config.json"
EXPECTED_PACKAGE = "com.bodyahmed77.fiftyfit"


def load_gs() -> dict:
    b64 = os.environ.get("GOOGLE_SERVICES_JSON_BASE64") or os.environ.get("GS_B64")
    if b64:
        raw = base64.b64decode(b64)
        return json.loads(raw.decode("utf-8"))
    path = Path(os.environ.get("GOOGLE_SERVICES_JSON", "android/app/google-services.json"))
    if not path.is_file():
        path = ROOT / "android" / "app" / "google-services.json"
    if not path.is_file():
        raise SystemExit("No google-services.json available (set GOOGLE_SERVICES_JSON_BASE64 or path)")
    return json.loads(path.read_text(encoding="utf-8"))


def find_web_client_id(data: dict) -> str:
    for client in data.get("client") or []:
        for oa in client.get("oauth_client") or []:
            if oa.get("client_type") == 3 and oa.get("client_id"):
                return str(oa["client_id"]).strip()
    for client in data.get("client") or []:
        for oa in client.get("oauth_client") or []:
            cid = (oa.get("client_id") or "").strip()
            if cid.endswith(".apps.googleusercontent.com") and not oa.get("android_info"):
                return cid
    raise SystemExit("No Web OAuth client_id (client_type 3) found in google-services.json")


def find_android_clients(data: dict) -> list[dict]:
    return [
        client
        for client in data.get("client") or []
        if ((client.get("client_info") or {}).get("android_client_info") or {}).get("package_name") == EXPECTED_PACKAGE
    ]


def validate_config(web_client_id: str) -> None:
    if not CAP_CONFIG.is_file():
        raise SystemExit("capacitor.config.json is missing")
    config = json.loads(CAP_CONFIG.read_text(encoding="utf-8"))
    app_id = str(config.get("appId") or "")
    if app_id != EXPECTED_PACKAGE:
        raise SystemExit(f"capacitor.config.json appId mismatch: {app_id!r} != {EXPECTED_PACKAGE!r}")

    auth = ((config.get("plugins") or {}).get("FirebaseAuthentication") or {})
    providers = auth.get("providers") or []
    if "google.com" not in providers:
        raise SystemExit("FirebaseAuthentication.providers does not include google.com")

    configured = str(auth.get("googleWebClientId") or "").strip()
    if configured != web_client_id:
        raise SystemExit(
            "Google Web OAuth client mismatch: "
            f"google-services.json={web_client_id!r}, capacitor.config.json={configured or '(missing)'!r}"
        )

    android_clients = find_android_clients(data=load_gs())
    if not android_clients:
        raise SystemExit(f"google-services.json has no Android client for {EXPECTED_PACKAGE}")


def main() -> None:
    data = load_gs()
    client_id = find_web_client_id(data)
    validate_config(client_id)
    content = (
        "/**\n"
        " * Google OAuth Web client ID (type 3 in google-services.json).\n"
        " * Generated by scripts/extract-google-web-client-id.py — do not edit by hand.\n"
        " */\n"
        f'export const GOOGLE_WEB_CLIENT_ID = "{client_id}";\n'
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"Google OAuth preflight OK: package={EXPECTED_PACKAGE}, webClientId=…{client_id[-24:]}")
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
