#!/usr/bin/env python3
"""Extract the Web (client_type 3) OAuth client_id from google-services.json
and write it into src/googleWebClientId.js for the Android external-browser flow.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "googleWebClientId.js"


def load_gs() -> dict:
    b64 = os.environ.get("GOOGLE_SERVICES_JSON_BASE64") or os.environ.get("GS_B64")
    if b64:
        import base64

        raw = base64.b64decode(b64)
        return json.loads(raw.decode("utf-8"))
    path = Path(os.environ.get("GOOGLE_SERVICES_JSON", "android/app/google-services.json"))
    if not path.is_file():
        path = ROOT / "android" / "app" / "google-services.json"
    if not path.is_file():
        raise SystemExit(
            "No google-services.json available (set GOOGLE_SERVICES_JSON_BASE64 or path)"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def find_web_client_id(data: dict) -> str:
    for client in data.get("client") or []:
        for oa in client.get("oauth_client") or []:
            if oa.get("client_type") == 3 and oa.get("client_id"):
                return str(oa["client_id"]).strip()
    for client in data.get("client") or []:
        for oa in client.get("oauth_client") or []:
            cid = (oa.get("client_id") or "").strip()
            if cid.endswith(".apps.googleusercontent.com") and not oa.get("android_info"):
                return cid
    raise SystemExit("No Web OAuth client_id (client_type 3) found in google-services.json")


def main() -> None:
    data = load_gs()
    client_id = find_web_client_id(data)
    content = (
        "/**\n"
        " * Google OAuth **Web** client ID (type 3 in google-services.json).\n"
        " * Generated by scripts/extract-google-web-client-id.py — do not edit by hand.\n"
        " */\n"
        f'export const GOOGLE_WEB_CLIENT_ID = "{client_id}";\n'
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} (…{client_id[-24:]})")


if __name__ == "__main__":
    main()
